-- 购物车表
CREATE TABLE IF NOT EXISTS cart (
  cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_user_id INTEGER NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  cart_product_id INTEGER NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  cart_quantity INTEGER NOT NULL DEFAULT 1,
  cart_selected_size VARCHAR(10),
  cart_selected_color VARCHAR(20),
  cart_create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 为用户ID和商品ID创建唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_cart_user_product ON cart(cart_user_id, cart_product_id);

-- 为用户ID创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_cart_user_id ON cart(cart_user_id);

-- 启用RLS（行级安全）
ALTER TABLE cart ENABLE ROW LEVEL SECURITY;

-- 创建RLS策略：用户只能访问自己的购物车
CREATE POLICY "Users can view own cart items" ON cart
  FOR SELECT USING (auth.uid()::text = cart_user_id::text);
  
CREATE POLICY "Users can insert own cart items" ON cart
  FOR INSERT WITH CHECK (auth.uid()::text = cart_user_id::text);
  
CREATE POLICY "Users can update own cart items" ON cart
  FOR UPDATE USING (auth.uid()::text = cart_user_id::text);
  
CREATE POLICY "Users can delete own cart items" ON cart
  FOR DELETE USING (auth.uid()::text = cart_user_id::text);