-- ============================================
-- 购物车表完整修复脚本（适用于自定义认证系统）
-- ============================================
-- 此脚本会：
-- 1. 创建购物车表（如果不存在）
-- 2. 禁用或修复RLS策略以适配自定义认证
-- ============================================

-- 步骤1：创建购物车表（如果不存在）
CREATE TABLE IF NOT EXISTS cart (
  cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_user_id INTEGER NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  cart_product_id INTEGER NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  cart_quantity INTEGER NOT NULL DEFAULT 1,
  cart_selected_size VARCHAR(10),
  cart_selected_color VARCHAR(20),
  cart_create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 步骤2：创建索引（如果不存在）
CREATE UNIQUE INDEX IF NOT EXISTS idx_cart_user_product ON cart(cart_user_id, cart_product_id);
CREATE INDEX IF NOT EXISTS idx_cart_user_id ON cart(cart_user_id);

-- 步骤3：删除可能存在的旧RLS策略（使用auth.uid()的策略）
DROP POLICY IF EXISTS "Users can view own cart items" ON cart;
DROP POLICY IF EXISTS "Users can insert own cart items" ON cart;
DROP POLICY IF EXISTS "Users can update own cart items" ON cart;
DROP POLICY IF EXISTS "Users can delete own cart items" ON cart;
DROP POLICY IF EXISTS "Allow all cart operations" ON cart;

-- 步骤4：禁用RLS（推荐用于开发环境，使用自定义认证时）
-- 因为您的应用使用自定义token认证，不是Supabase Auth
-- 所以需要禁用RLS，或者在后端使用Service Role Key
ALTER TABLE cart DISABLE ROW LEVEL SECURITY;

-- ============================================
-- 完成！
-- ============================================
-- 现在购物车表应该可以正常工作了
-- 如果仍有问题，请确保后端配置了 SUPABASE_SERVICE_ROLE_KEY
-- ============================================

